### PR TITLE
Add info about public access scope

### PR DESCRIPTION
**Pull request by joaomatos-dme**

### CODE REVIEW

**Comment by TiagoMF20** [comment]
My suggestion for the "Authorization Scopes" definition:

Authorization scopes are definitions used to protect resources, by enabling associated policies that ensure a connecting client has the access permissions required for a given resource.

**Comment by hector-rodriguez** [comment]
I agree with Tiago's definition. We should clearly differentiate between protection scopes and the concept of policies, which now will reside on the PDP...

**Review by hector-rodriguez — COMMENTED** [review]
I would also recommend to add a section named 

"Authenticated Access" that implies the only restriction is for the user to have an ongoing session (no authorization layer required)

**Comment by TiagoMF20** [comment]
I would just change the definition of the Authenticated Access from:
"This scope requires the user to have an ongoing active session."
to:
"This scope is associated with a policy that verifies if the user, making the request, has an ongoing active session.

**Review by TiagoMF20 — APPROVED** [review]

**Review by hector-rodriguez — APPROVED** [review]

**Pull request merged**
